openapi: 3.0.9
info:
  title: Gestão de Reciclagens
  version: '1.0'
servers:
  - url: http://localhost:3000
components:
  schemas:
    Reciclagem:
      type: object
      properties:
        item:
          type: string
        imagem:
          type: string
        peso: 
          type: number
        pontos:
          type: number
        data:
          type: string
        usuario:
          type: string
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT  
paths:
  /reciclagem/{id}:
    get:
      operationId: criarReciclagem
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Id do usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reciclagem criado com sucesso!
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado: 
                    type: string
                  reciclagem:
                    type: array
                    items: 
                      $ref: '#/components/schemas/Reciclagem'
        '404':
          description: Usuário não encontrado!
        '400':
          description: Parâmetros inválidos!
        '401':
          description: Usuário não atuorizado a realizar a operação!